version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: 'bookstore'
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD : 'admin'
    ports:
      - "5432:5432"
    restart: always
  app:
    build: .
    command: python run.py db init python run.py db migrate
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
